M48
; DRILL file {KiCad (6.0.11)} date Fri Feb 24 20:07:29 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-24T20:07:29+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.448Y-2.1008
X3.448Y-4.6992
X5.0819Y-2.1008
X5.0819Y-4.6992
T0
M30
